import yaml
from pathlib import Path

def generate_claim_register():
    root = Path(__file__).resolve().parent.parent
    claims_file = root / "career-data" / "facts" / "claims.yml"
    out_file = root / "CLAIM_REGISTER.md"
    
    with open(claims_file, 'r', encoding='utf-8') as f:
        data = yaml.safe_load(f)
        
    lines = [
        "# CLAIM_REGISTER.md",
        "",
        "> **Notice**: This file is generated automatically from `career-data/facts/claims.yml`.",
        "> Do not edit this file directly. All changes must be made to the canonical YAML source.",
        "",
        "## Claim Register",
        ""
    ]
    
    for claim in data.get('claims', []):
        lines.append(f"### {claim['id']} — {claim.get('type', 'General').capitalize()} Claim")
        lines.append("")
        lines.append("| Field | Value |")
        lines.append("|-------|-------|")
        lines.append(f"| **Canonical Wording** | `{claim.get('canonical', '')}` |")
        lines.append(f"| **Status** | {claim.get('status', 'active')} |")
        lines.append(f"| **Risk Level** | {claim.get('risk', 'medium').upper()} |")
        lines.append(f"| **Supported by Evidence IDs** | {', '.join(claim.get('evidence', []))} |")
        lines.append(f"| **Used In** | {', '.join(claim.get('presentation_assets', []))} |")
        lines.append("")
        lines.append("---")
        lines.append("")
        
    out_file.write_text("\n".join(lines), encoding="utf-8")
    
if __name__ == "__main__":
    generate_claim_register()
