import json
import sys
from pathlib import Path

def generate_recruiter_pack(view_dir, out_dir):
    view_path = view_dir / 'recruiter_view.json'
    if not view_path.exists():
        print(f"Error: {view_path} not found.")
        sys.exit(1)
        
    with open(view_path, 'r', encoding='utf-8') as f:
        view = json.load(f)
        
    # Generate HTML or Markdown
    markdown = f"""# {view.get('candidate_name')}
## {view.get('professional_title')}

*Generated by Career OS v4.0 Pipeline*
"""
    
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / 'RECRUITER_PACK.md'
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write(markdown)
        
    print(f"Recruiter Pack generated at {out_path}.")

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--view-dir", default="career-data/view_models")
    parser.add_argument("--out-dir", default="recruiter_packs")
    args = parser.parse_args()
    
    root = Path(__file__).parent.parent
    view_dir = root / args.view_dir
    out_dir = root / args.out_dir
    generate_recruiter_pack(view_dir, out_dir)
